# Generated by Django 3.2.4 on 2022-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=80000)),
                ('short_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
